### ISSUE TITLE
All cores not working properly

### ISSUE THREAD

**Issue by latot** [vlarmet/cppRouting#8]
Hi, I has tryied to use the ```allcores```, but then I notice it, is not using all my cores D:

Well, maybe technically is using it, but every core is used half of it..., I don't know how it works, but would be great if the option get the best performance over all cores.

Thx!

**Comment by vlarmet** [comment]
Hi,

I don't know, maybe you can try with cppRouting 3.1 (which will be on CRAN in a few days)
