### ISSUE TITLE
Dijkstra algorithm in get_path_pair

### ISSUE THREAD

**Issue by kchalkowski** [vlarmet/cppRouting#9]
Hey,

First off, thank you for this useful and efficient package.

I was using get_path_pair in a simulation, using the Dijkstra algorithm to get the shortest path between an origin and destination. I recently installed this package on a remote computer to run the simulation, and it no longer works as expected. Now, when I run with the same code in the new installed version, my result is this: 

`1 new("standardGeneric", .Data = function (x)                              
2 standardGeneric("res"), generic = structure("res", package = "terra"),   
3     package = "terra", group = list(), valueClass = character(0),        
4     signature = "x", default = NULL, skeleton = (function (x)            
5     stop("invalid call in method dispatch to 'res' (no default method)", 
6         domain = NA))(x))`

and this is the function used to get that result:

`spp=get_path_pair(gr,cno,cnd,algorithm="Dijkstra")`

 I think what's maybe happening is that it isn't assigning anything to res, the returned object, because I'm calling an algorithm name that isn't there anymore in the most recent commit? I noticed there is only 'bi' and 'nbd' now in the function. However, I tried the 'bi' option and I get the same result. Any thoughts on what is going on here?

Thank you,
Kayleigh

**Comment by kchalkowski** [comment]
For now, I just ended up uninstalling the new version and reinstalling version 2.0, which is what I had been using on my local machine. Now, it is running great again. However, if you have any advice on something I may be doing wrong in the new vs old version, happy to hear it. Thank you again for this package!!

**Comment by vlarmet** [comment]
Hi,
Can you provide a reproducible example, please ?

**Comment by vlarmet** [comment]
Dijkstra algorithm is implemented, it is called when : !(algorithm %in% c("bi", "NBA", "A*")).
It's weird because error message only mention terra package.
